stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw/data.csv
    params:
      - preprocess.random_state
      - preprocess.test_split
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - data/processed/train.csv
    params:
      - train.n_estimators
      - train.max_depth
      - train.random_state
    outs:
      - models/classifier.pkl

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - data/processed/test.csv
      - models/classifier.pkl
    metrics:
      - metrics/scores.json:
          cache: false
